version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: jane
      MYSQL_PASSWORD: P@ssword1234
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork

  api:
    build: ./backend/
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: 'jane'
      DB_PASSWORD: 'P@ssword1234'
      DB_DATABASE: test
    networks:
      - mynetwork

  web:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_HOST=localhost:5000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge